### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by damusix** [hapipal/schwifty#102]
As a developer I should be able to see schwifty typings so I can have an enhanced developer experience on my IDE / with typescript.

Please let me know if I can find them somewhere if exists before I get ahead of myself. I am willing to open a PR. It _should_ be easy enough given Objection has typings and this is a small layer on top. 

If there are any objections (pun intended 🙃), please advise!

**Comment by devinivy** [comment]
Hi!  These exist for schwifty, however I don't think anyone has moved them over to the @hapipal namespace.  Here's the prior version on DefinitelyTyped which should still largely be correct: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/schwifty
