### ISSUE TITLE
Plugin's knex instance should default to the root server's

### ISSUE THREAD

**Issue by devinivy** [hapipal/schwifty#12]
This is both,

1. when `Model.knexBind()`ing during init and,
2. when calling `request.knex()` and `server.knex()`.

**Comment by wswoodruff** [comment]
@devinivy Don't these lines cover this?
https://github.com/BigRoomStudios/schwifty/blob/master/lib/index.js#L176-L179

**Comment by devinivy** [comment]
Yeah, actually it sort of does.  I think I really just mean to update the behavior.  That sets a special root knex instance as the first knex instance that's specified in any plugin.  We would rather not rely on timing– the root knex instance should simply be the knex instance set when,

1. registering the plugin, or
2. calling `server.schwifty()` when `server` is the root server.

And it should be able to be specified at any point in time.  In short, this feature is really about making sure that "order doesn't matter" when it comes to plugins (and the root server) declaring their knex instances.

**Comment by wswoodruff** [comment]
Ok cool. So we're leaving it open for the root knex instance to be registered _possibly_ after some plugins have registered. Yeah that whole block can be changed then, and the Hoek.assert can be removed (the one mentioned in description of #9 )

**Comment by devinivy** [comment]
Yup, that block changed a fair amount in #13– would love some review!

**Comment by wswoodruff** [comment]
On it
