### ISSUE TITLE
Update to use objection v0.7's validators

### ISSUE THREAD

**Issue by devinivy** [hapipal/schwifty#23]
Objection is codifying the idea of "validators."  This is good for us, since we're using a non-default validation library (joi!).  Currently v0.7 is only in release-candidate phase, but when it comes out we'll want to make updates (shouldn't be giant!) and release the next version of schwifty.  We don't know exactly how it's going to timeout in relation to the release of schwifty v1, so let's not worry about it too much.

Let's just keep an eye on this for now, https://github.com/Vincit/objection.js/releases
Validator reference, https://github.com/Vincit/objection.js/commit/b553097a58f8b5dac7ba78d1e9c72a5885f306d5

**Comment by wswoodruff** [comment]
Sounds great! If we release first, we can have `greenkeeper` alert us

**Comment by devinivy** [comment]
Though I'm not sure greenkeeper lets you know about the status of peer deps! https://github.com/greenkeeperio/greenkeeper/issues/201
