### ISSUE TITLE
Support models() to returning a single model by name

### ISSUE THREAD

**Issue by devinivy** [hapipal/schwifty#25]
I wonder if it would be convenient if `request.models()` and `server.models()` could be used as such,
```
server.models('Movie');     // Returns Movie class
server.models('Dog');       // Returns null, since Dog is defined in another plugin.  Or throws hard??
server.models('Dog', true); // Returns Dog class defined in another plugin
```

**Comment by wswoodruff** [comment]
Yeah that rocks! It wouldn't be hard to do either

**Comment by devinivy** [comment]
Wouldn't be hard to do, just wondering if it's going overboard or extending the API surface area in unnecessary ways.  The thought has been stuck in my head since dogwater days, so figured I'd dump it here as a request/discussion. :)  The main upside I can imagine is that it could give a good, hard error if you're trying to access a model from another plugin, or a model that doesn't exist at all.

**Comment by mattboutet** [comment]
I like this.  It seems like a bit of functionality that might not be needed all the time, but which will inevitably be needed, and which we ought to have a clean way to handle it.

**Comment by devinivy** [comment]
I'm lining-up features for v2.  Final thoughts on this?  I'm a little ambivalent about it, especially in light of the fact that we can write this,
```js
const { Movie } = server.models();
```

**Comment by mattboutet** [comment]
I prefer this version - it feels cleaner.

**Comment by devinivy** [comment]
Agree!
