### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by alexisohayon** [hapipal/schwifty#52]
Hi!

Me again, sorry 😏 I've reading the doc again and again but still confused on what is the best practice to structure my project. For now I have an api folder with every models represented by a folder, containing the Model file, the routes etc... But as you register the models in the server file, how can I do it in each model.js file that I have?
I'm not sure I'm making myself clear, maybe a pic will help more:
![capture d ecran 2017-11-23 a 10 41 21](https://user-images.githubusercontent.com/781456/33166549-ec2dc3e2-d03a-11e7-9189-186f7b9af68e.png)

Thanks a lot, again :)

**Comment by devinivy** [comment]
Hey!  So, there are a few ways to fix your issue, especially with schwifty v4.

First, you may always register models within a plugin by calling `server.schwifty(models)`.  You can combine that with a tool like [require-dir](https://www.npmjs.com/package/require-dir) to automate your issue away pretty nicely.

In all versions of schwifty you may also pass a file to the `models` plugin option, and any models exported by that single file will automatically be registered with the server.  Now in schwifty v4 it also correctly attributes those models to the plugin that registered schwifty.  Remember, you can register schwifty as many times as you would like (i.e. in every plugin that uses it)!

Finally, and this is the method I use, there's [haute-couture](https://github.com/devinivy/haute-couture), which allows you to build hapi plugins simply by placing files in directories.  It supports schwifty by registering models found in the `models/` directory.  You can also configure haute-couture to use a different directory name, ignore other directories that it typically recognizes, etc.  And it plays well with the CLI tool [hpal](https://github.com/devinivy/hpal), which can generate basic model files for you automatically (e.g. `hpal make model User`).
