### ISSUE TITLE
Overriding model throws. How to override?

### ISSUE THREAD

**Issue by ozum** [hapipal/schwifty#58]
Hi,

I'm trying to follow suggested best practice [Extending schwifty models across plugins](https://hapipal.com/best-practices/schwifty-across-plugins#extending-schwifty-models-across-plugins). However I'm using `haute-couture` (hc) and hapipal boilerplate.

I put my model file in `lib/models/user.js` file, and `hc` registers my user model.

Then following best practice, conditional below throws exception `Model "User" has already been registered.`, because `hc` registered it.

```js
server.schwifty(options.Model || UserModel);
```

What do you suggest to follow best practice using `hc` while **keeping** my user model in `models` directory.

Thanks,

**Comment by devinivy** [comment]
You have a few options!

1.  Whenever you create an `index.js` file in a directory, haute-couture will ignore the other files in that directory.  You can use this to implement anything custom that you'd like to do without haute-couture getting in your way.  So, `models/index.js` could export your other models `[Pets, Groups, Posts]` but exclude `User`.  This could be further automated using a module like [`require-dir`](https://github.com/aseemk/requireDir).
2. haute-couture ignores deeply nested directories.  So if you have some models you want hc to register, and others that you do not, just place the ones you don't want registered in a subdirectory e.g. `models/base-classes/user.js`
3. If you have a plugin in which you want haute-couture to completely ignore a given directory, you can configure that in `.hc.js` like so (or pass the same options as an amendment directly to [`Hc.using()`](https://hapipal.com/docs/haute-couture#hautecoutureusingdirname-amendments)),
   ```js
   // lib/.hc.js
   module.exports = {
       remove: ['models']
   };
   ```

**Comment by ozum** [comment]
@devinivy thank you for the answer.

If possible, as a feature request, please add an option to `schwifty()` method to override previously added model such as:

```js
// CAVEAT: NOT WORKING CODE
server.schwifty(options.Model || UserModel, { override: true });
```

I'm sure this would be useful for some other use cases too.

**Comment by wswoodruff** [comment]
@ozum Overriding models is on the horizon for us, it's a feature we want too and have been working towards it -- be on the lookout for more overriding in the future ✨

**Comment by ozum** [comment]
Currently I'm overriding using some complex require tangling, having that feature will be much more elegant.

Also related to override; 

If you implement this feature, also consider to add some options to `Schwifty.assertCompatible()`. In some scenarios, table name could be changed when extending a base model. It is not a big deal which can be solved using `instanceof`, but would be handy.

**Comment by devinivy** [comment]
I am open to adding some options to `assertCompatible()`— anyone feel free to open an issue with a specific feature proposal.  With schwifty v5.3.0 out and #84 being complete, I think the new sandboxing feature covers the use case described in this issue.
