### ISSUE TITLE
Question: How to reduce coupling

### ISSUE THREAD

**Issue by ozum** [hapipal/schwifty#59]
Hi,

I generate my schwifty models from database using code generation tool. Tool generates Joi schema as well. I use model's joi schema as a base for validation in routes.

Overly simplified example:
**routes/users.js**
```js
const UserModel = require("../models").User; // This causes coupling to model file

module.exports = {
  method: "post",
  path: "/users",
  config: {
    validate: { payload: UserModel.joiSchema },
    response: {
      schema: UserModel.responseSchema, // based on static get joiSchema()
    },
  },
  handler: async request => {
    const { User } = request.models();
    return User.query();
  },
}
```
My principles here are:
* schwifty greatly decreases coupling to model files via `request.models()`
* Reusing joi schema in model and routes is good for DRY.

And my question is:
To reuse joi schema from model, I have to require model file and this causes coupling. Is there any way to avoid coupling while accessing static methods of classes? Perhaps a static method from schwifty to access models (of course not instances but classes)

Thanks in advance.

**Comment by mattboutet** [comment]
Schwifty models are also available on the server, so you could try something like:

`routes/users.js`
```javascript

module.exports = (server) => {

  const { UserModel } = server.models();
  return {
    method: "post",
    path: "/users",
    config: {
      validate: { payload: UserModel.joiSchema },
      response: {
        schema: UserModel.responseSchema, // based on static get joiSchema()
      },
    },
    handler: async request => {
      const { User } = request.models();
      return User.query();
    }
  };
}
```

**Comment by ozum** [comment]
@mattboutet, that worked thanks a lot.

Is `(server) => {}` a feature of `haute-couture`? I couldn't find it in docs. (I may missed it, since 30 different doc tabs are open in my screen).

**Comment by wswoodruff** [comment]
@ozum Yes it's a feature of `haute-couture` to be able to export a function that receives the server, or a single route, or an array of routes

**Comment by mattboutet** [comment]
@ozum - it's not as explicit as maybe it could be in the docs, but if you look at https://github.com/hapipal/haute-couture/blob/master/API.md#files-and-directories you'll see:

>Lastly, files can always export a function with signature function(server, options) that returns the intended value or array of values.

edit: worth noting that this doesn't just work for `routes` - I've found it useful sometimes in other contexts as well.

**Comment by devinivy** [comment]
Thanks all!  Closing, but we can reopen this if we decide there's something actionable to do.  Feel free to continue the conversation.  As always, improvements to the docs are welcome!

**Comment by ozum** [comment]
> Lastly, files can always export a function with signature function(server, options) that returns the intended value or array of values.

@mattboutet I missed it, because I explicitly looked directly into [routes](https://github.com/hapipal/haute-couture/blob/master/API.md#routes) section.

@devinivy IMHO, it would be better to add this detail in each related section of API.

Instead of 
> * routes.js - export an array of options.
> * routes/index.js - export an array of options.
> ...

something like
> * routes.js - export an array of options or a function with signature `function(server, options)` that returns it.
> * routes/index.js - export an array of options or a function with signature `function(server, options)` that returns it.
> * routes/route-id.js - export options or a function with signature `function(server, options)` that returns it. If options is a single route config object, the route's config.id will be assigned 'route-id' from the filename if it isn't already specified. The filename could just as easily represent a group of routes (rather than an id) and the file could export an array of route configs.

I can do a PR if you are OK with that change or have a better wording.

**Comment by devinivy** [comment]
@ozum thanks for all the thought!  We would happily take a PR for that change.

**Comment by ozum** [comment]
[Here](https://github.com/hapipal/haute-couture/pull/43) it is.

**Comment by rickysullivan** [comment]
Call me crazy, but I wanted to use my Schwifty model's Joi schema to validate my PATCH payload. However, being a PATCH call, not all the model's fields are required, even though some of my schema keys are `.required()`. I have meta key called `allowUpdate` which I use to filter the schema.

```
{
    method: "PATCH",
    path: "/datacentres/{dc}/clients/{client}",
    options: {
        description: "Update `Client` in `Data Centre`.",
        payload: {
        allow: "application/json"
        },
        validate: {
            payload: Joi.object().keys({
                ...Object.assign(
                {},
                ..._(ClientModel.joiSchema.describe().children)
                    .pickBy(child => _.find(child.meta, { allowUpdate: true }))
                    .keys()
                    .value()
                    .map(field => ({
                        [field]: Joi.reach(ClientModel.joiSchema, field)
                    }))
                )
            })
        },
        auth: {
            scope: ["ADMIN", "SUPERADMIN"]
        },
        handler: async (request, h) => {
            //Do some function to add to DB.
        }
    }
}
```
Is this nuts?

**Comment by devinivy** [comment]
It makes sense to me, but I think you might be able to avoid the hassle!  Objection also needs to validate "patch" objects (ignoring `required()` fields), so schwifty has this idea built-in.  See [`Model.getJoiSchema(patch)`](https://github.com/hapipal/schwifty/blob/master/API.md#getjoischemapatch).
```js
    payload: Model.getJoiSchema(true)
```

Alternatively you can also chain directly off the model's schema to allow/forbid certain keys:
```js
    payload: Model.getJoiSchema()
        .optionalKeys('x')
        .forbiddenKeys('y')
```

**Comment by rickysullivan** [comment]
Bugger me. That's what I was looking for. Thanks for the tip.

**Comment by rickysullivan** [comment]
So, while upgrading Hapi, Schwifty and Joi to the latest versions. How do I mark forbidden keys? I'm getting `AssertionError [ERR_ASSERTION]: Invalid schema content` now.

**Comment by rickysullivan** [comment]
```
validate: {
  payload: DCClientModel.getJoiSchema().forbiddenKeys([
    "Client",
    "DatabaseName"
  ])
}
