### ISSUE TITLE
Register multiple knex databases

### ISSUE THREAD

**Issue by kanil4** [hapipal/schwifty#67]
Is there a way for Schwifty to handle multiple database connections while using knex plugin? I am looking for a way to connect to 2 different DB's so as i can define 2 different DB hosts. 
Here is how i have added the very first entry ->

`{
        plugin: Schwifty,
        options: [{
            knex: {
                client: 'postgresql',
                connection: {
                    user: process.env.AWS_DB_USER,
                    host: process.env.AWS_DB_HOST,
                    database: process.env.AWS_DB,
                    password: process.env.AWS_DB_PASSWORD,
                    port: process.env.AWS_DB_PORT
                },
                pool: {
                    min: 2,
                    max: 10
                }
            }
        }]
    }`

**Comment by devinivy** [comment]
Yeah, there are some good ways to approach this with schwifty!  Check-out this answer to a really similar question and let us know if it helps clear things up: https://github.com/hapipal/haute-couture/issues/54#issuecomment-486801609
